# Generated by Django 2.1 on 2018-11-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181111_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillscategory',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='skill',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='skills'),
        ),
        migrations.AlterField(
            model_name='skillscategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='skills'),
        ),
    ]
