# Generated by Django 2.1 on 2018-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181111_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(default='4665 rue de Mentana', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('ca', 'Canada')], default='ca', max_length=3, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('qc', 'Quebec')], default='qc', max_length=50, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='H2J3B7', max_length=30, verbose_name='Zip code'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
