version: "2"

services:
  db:
    image: postgres:11.0-alpine
  web:
    build: .
    tty: true
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/neighbor
    ports:
      - "8000:8000"
    depends_on:
      - db
